name = "renelaird"
compatibility_date = "2025-01-01"

# Cloudflare Pages static site root
pages_build_output_dir = "./"

# Connect to your D1 database
[[d1_databases]]
binding = "dreamgirl_db"
database_name = "dreamgirl-db"
database_id = "31f7672d-162b-43d2-a89d-61ee42876ae1"
