name: Publish Vocab to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-vocab:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Vocab to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vocab
          destination_dir: vocab
